### ISSUE TITLE
Augurk publish azure devops task does not fail on authentication error

### ISSUE THREAD

**Issue by rouke-broersma** [Augurk/Augurk.CommandLine#20]
When augurkcli receives an authentication error on publish, the azure devops task does not mark the build as failed or warning:

![image](https://user-images.githubusercontent.com/3595932/58029927-e94e4680-7b1d-11e9-8626-6edf303efb6c.png)

**Comment by jmezach** [comment]
Hmm, looks like we do [check the error code](https://github.com/Augurk/Augurk.CommandLine/blob/b3168cdeee0afd7fa01f76948892068a53424693/src/Augurk.CommandLine/Commands/PublishCommand.cs#L106) and write an error message to the output, but then simply continue with the next feature, rather than returning a non-zero exit code.

Should be an easy enough fix. A PR would be greatly appreciated.

**Comment by jmezach** [comment]
This fix has been released as 4.0.1 of the Augurk CLI.
